# Generated by Django 5.2.6 on 2025-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundiprofile',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='fundi_ids/'),
        ),
        migrations.AddField(
            model_name='fundiprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='fundi_photos/'),
        ),
        migrations.AddField(
            model_name='fundiprofile',
            name='verification_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fundiprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
