# Generated by Django 5.2.6 on 2025-09-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fundiprofile_id_document_fundiprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundiprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundiprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
