# Generated by Django 5.2.6 on 2025-09-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fundiprofile_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='customer_ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/'),
        ),
    ]
