# Generated by Django 5.2.6 on 2025-09-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_otp_code_user_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.CharField(default='fundi', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(default=list),
        ),
    ]
