# Generated by Django 5.2.6 on 2025-09-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_review_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
